### ISSUE TITLE
Agregar espacio al pié de las páginas que lo necesiten

### ISSUE THREAD

**Issue by lgiudice** [uqbar-project/wisit15-site-harpjs#17]
Por ejemplo, la página de [inscripción](http://uqbar-project.github.io/wisit15-site-harpjs/inscripcion/) se ve así:

![pie de inscripcion](https://cloud.githubusercontent.com/assets/1686015/8678025/b5a93f3c-2a28-11e5-86e0-4169d0660040.png)

Y queda medio feo.

**Comment by bossiernesto** [comment]
Alguien puede verificar esto en otro navegador? Gracias

**Comment by lgiudice** [comment]
Yo lo probé en firefox y chrome y funca.

2015-07-27 13:02 GMT-03:00 Ernesto Bossi notifications@github.com:

**Comment by bossiernesto** [comment]
Groso, mil gracias cierro el ticket.
