### ISSUE TITLE
Agregar algún tipo de feedback en la navbar

### ISSUE THREAD

**Issue by lgiudice** [uqbar-project/wisit15-site-harpjs#18]
En este momento, no se sabe a simple vista dónde está uno parado (si no se está viendo el título de la página).
Si se agrega algún cambio en el tono del azul de la navbar correspondiente a la página seleccionada, ese problema de navegación queda resuelto.

Algo similar pasa cuando uno hace hover sobre algún elemento de la barra de navegación, no hay feedback.

**Comment by bossiernesto** [comment]
Esto ya fue agregado en el commit https://github.com/bossiernesto/wisit15-site-harpjs/commit/d4c2c4be1c1038216e05f52968c5b5de4abaf07e
