### ISSUE TITLE
Fotito de los speakers acompañando las bios

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wisit15-site-harpjs#34]
Me imagino algo así:

![image](https://cloud.githubusercontent.com/assets/1585835/9646119/dbadc75c-51a6-11e5-81e2-a937e11e6084.png)

**Comment by npasserini** [comment]
Estaría bueno pero es un laburo conseguir todas las fotos, no me opongo
pero no me puedo comprometer a hacerlo.

**Comment by faloi** [comment]
Entre LinkedIn y GitHubs las conseguimos, @AlvarezAriel me da una mano con eso :smile:

**Comment by npasserini** [comment]
Genial entonces.
