### ISSUE TITLE
El highlighting de la navbar es distinto para sponsors

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wisit15-site-harpjs#47]
(En comparación con otras páginas.)

**Comment by bossiernesto** [comment]
Revise el sitio con la versión tanto en lo que esta deployeado para master como para dev, y no encontre una diferencia en si con las otras páginas, lo que si veo es que la barra cuando no esta marcada en ninguno de los botones del navbar, cuando esta en /, ahi solo se afina, se podría fixear eso. 

Si tenes alguna captura o algo para ver y tratar de reproducir el error mejor y para entender en que esta fallando.

Gracias

**Comment by npasserini** [comment]
Tenés razón, era un problema de caché.
